# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget lib)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target lib
add_library(lib STATIC IMPORTED)

set_target_properties(lib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CUTTLEFISH_HAS_S3TC=1;CUTTLEFISH_HAS_ETC=1;CUTTLEFISH_HAS_ASTC=1;CUTTLEFISH_HAS_PVRTC=1"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/lib/include;C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/build/lib/include"
  INTERFACE_LINK_LIBRARIES "C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/lib/PVRTexToolLib/Windows_x86_64/PVRTexLib.lib"
)

# Import target "lib" for configuration "Debug"
set_property(TARGET lib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/build/output/Debug/cuttlefishd.lib"
  )

# Import target "lib" for configuration "Release"
set_property(TARGET lib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/build/output/Release/cuttlefish.lib"
  )

# Import target "lib" for configuration "MinSizeRel"
set_property(TARGET lib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/build/output/MinSizeRel/cuttlefish.lib"
  )

# Import target "lib" for configuration "RelWithDebInfo"
set_property(TARGET lib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/nesquack/Documents/GitReposLocal/Cuttlefish/build/output/RelWithDebInfo/cuttlefish.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
