#if defined(_MSC_VER)
#define EXPORT __declspec(dllexport)
#elif defined(__GNUC__)
#define EXPORT __attribute__((visibility("default")))
#endif

EXPORT int PVRTexLib_AddMetaData() {return 0;}
EXPORT int PVRTexLib_AddPaddingMetaData() {return 0;}
EXPORT int PVRTexLib_Bleed() {return 0;}
EXPORT int PVRTexLib_BlendDiff() {return 0;}
EXPORT int PVRTexLib_BorderTexture() {return 0;}
EXPORT int PVRTexLib_ColourDiff() {return 0;}
EXPORT int PVRTexLib_ColourMIPMaps() {return 0;}
EXPORT int PVRTexLib_CopyTexture() {return 0;}
EXPORT int PVRTexLib_CopyTextureChannels() {return 0;}
EXPORT int PVRTexLib_CopyTextureHeader() {return 0;}
EXPORT int PVRTexLib_CreateTexture() {return 0;}
EXPORT int PVRTexLib_CreateTextureFromData() {return 0;}
EXPORT int PVRTexLib_CreateTextureFromFile() {return 0;}
EXPORT int PVRTexLib_CreateTextureHeader() {return 0;}
EXPORT int PVRTexLib_CreateTextureHeaderFromHeader() {return 0;}
EXPORT int PVRTexLib_Decompress() {return 0;}
EXPORT int PVRTexLib_DestroyTexture() {return 0;}
EXPORT int PVRTexLib_DestroyTextureHeader() {return 0;}
EXPORT int PVRTexLib_EquiRectToCubeMap() {return 0;}
EXPORT int PVRTexLib_FlipTexture() {return 0;}
EXPORT int PVRTexLib_GenerateDiffuseIrradianceCubeMap() {return 0;}
EXPORT int PVRTexLib_GenerateMIPMaps() {return 0;}
EXPORT int PVRTexLib_GenerateNormalMap() {return 0;}
EXPORT int PVRTexLib_GeneratePreFilteredSpecularCubeMap() {return 0;}
EXPORT unsigned int PVRTexLib_GetFormatBitsPerPixel(unsigned long long u64PixelFormat) {return 12345;}
EXPORT int PVRTexLib_GetMetaDataBlock() {return 0;}
EXPORT int PVRTexLib_GetNumTextureAtlasMembers() {return 0;}
EXPORT int PVRTexLib_GetPixelFormatMinDims() {return 0;}
EXPORT int PVRTexLib_GetTextureAtlasData() {return 0;}
EXPORT int PVRTexLib_GetTextureBitsPerPixel() {return 0;}
EXPORT int PVRTexLib_GetTextureBorder() {return 0;}
EXPORT int PVRTexLib_GetTextureBumpMapOrder() {return 0;}
EXPORT int PVRTexLib_GetTextureBumpMapScale() {return 0;}
EXPORT int PVRTexLib_GetTextureChannelCount() {return 0;}
EXPORT int PVRTexLib_GetTextureChannelType() {return 0;}
EXPORT int PVRTexLib_GetTextureColourSpace() {return 0;}
EXPORT int PVRTexLib_GetTextureCubeMapOrder() {return 0;}
EXPORT int PVRTexLib_GetTextureD3DFormat() {return 0;}
EXPORT int PVRTexLib_GetTextureDXGIFormat() {return 0;}
EXPORT int PVRTexLib_GetTextureDataConstPtr() {return 0;}
EXPORT int PVRTexLib_GetTextureDataPtr() {return 0;}
EXPORT int PVRTexLib_GetTextureDataSize() {return 0;}
EXPORT int PVRTexLib_GetTextureDepth() {return 0;}
EXPORT int PVRTexLib_GetTextureFormatMinDims() {return 0;}
EXPORT int PVRTexLib_GetTextureHeader() {return 0;}
EXPORT int PVRTexLib_GetTextureHeaderW() {return 0;}
EXPORT int PVRTexLib_GetTextureHeight() {return 0;}
EXPORT int PVRTexLib_GetTextureIsBumpMap() {return 0;}
EXPORT int PVRTexLib_GetTextureIsFileCompressed() {return 0;}
EXPORT int PVRTexLib_GetTextureIsPreMultiplied() {return 0;}
EXPORT int PVRTexLib_GetTextureMetaDataSize() {return 0;}
EXPORT int PVRTexLib_GetTextureNumArrayMembers() {return 0;}
EXPORT int PVRTexLib_GetTextureNumFaces() {return 0;}
EXPORT int PVRTexLib_GetTextureNumMipMapLevels() {return 0;}
EXPORT int PVRTexLib_GetTextureOpenGLESFormat() {return 0;}
EXPORT int PVRTexLib_GetTextureOpenGLFormat() {return 0;}
EXPORT int PVRTexLib_GetTextureOrientation() {return 0;}
EXPORT int PVRTexLib_GetTextureParts() {return 0;}
EXPORT int PVRTexLib_GetTexturePixelFormat() {return 0;}
EXPORT int PVRTexLib_GetTextureSize() {return 0;}
EXPORT int PVRTexLib_GetTextureVulkanFormat() {return 0;}
EXPORT int PVRTexLib_GetTextureWidth() {return 0;}
EXPORT int PVRTexLib_IsTextureMultiPart() {return 0;}
EXPORT int PVRTexLib_MaxDifference() {return 0;}
EXPORT int PVRTexLib_MeanError() {return 0;}
EXPORT int PVRTexLib_MeanSquaredError() {return 0;}
EXPORT int PVRTexLib_MoveTexture() {return 0;}
EXPORT int PVRTexLib_PeakSignalToNoiseRatio() {return 0;}
EXPORT int PVRTexLib_PreMultiplyAlpha() {return 0;}
EXPORT int PVRTexLib_RemoveMetaData() {return 0;}
EXPORT int PVRTexLib_ResizeTexture() {return 0;}
EXPORT int PVRTexLib_ResizeTextureCanvas() {return 0;}
EXPORT int PVRTexLib_RootMeanSquaredError() {return 0;}
EXPORT int PVRTexLib_RotateTexture() {return 0;}
EXPORT int PVRTexLib_SaveSurfaceToImageFile() {return 0;}
EXPORT int PVRTexLib_SaveTextureToFile() {return 0;}
EXPORT int PVRTexLib_SaveTextureToLegacyPVRFile() {return 0;}
EXPORT int PVRTexLib_SaveTextureToMemory() {return 0;}
EXPORT int PVRTexLib_SetDefaultTextureHeaderParams() {return 0;}
EXPORT int PVRTexLib_SetTextureAtlas() {return 0;}
EXPORT int PVRTexLib_SetTextureBorder() {return 0;}
EXPORT int PVRTexLib_SetTextureBumpMap() {return 0;}
EXPORT int PVRTexLib_SetTextureChannelType() {return 0;}
EXPORT int PVRTexLib_SetTextureChannels() {return 0;}
EXPORT int PVRTexLib_SetTextureChannelsFloat() {return 0;}
EXPORT int PVRTexLib_SetTextureColourSpace() {return 0;}
EXPORT int PVRTexLib_SetTextureCubeMapOrder() {return 0;}
EXPORT int PVRTexLib_SetTextureD3DFormat() {return 0;}
EXPORT int PVRTexLib_SetTextureDXGIFormat() {return 0;}
EXPORT int PVRTexLib_SetTextureDepth() {return 0;}
EXPORT int PVRTexLib_SetTextureHeight() {return 0;}
EXPORT int PVRTexLib_SetTextureIsFileCompressed() {return 0;}
EXPORT int PVRTexLib_SetTextureIsPreMultiplied() {return 0;}
EXPORT int PVRTexLib_SetTextureNumArrayMembers() {return 0;}
EXPORT int PVRTexLib_SetTextureNumFaces() {return 0;}
EXPORT int PVRTexLib_SetTextureNumMIPLevels() {return 0;}
EXPORT int PVRTexLib_SetTextureOGLESFormat() {return 0;}
EXPORT int PVRTexLib_SetTextureOGLFormat() {return 0;}
EXPORT int PVRTexLib_SetTextureOrientation() {return 0;}
EXPORT int PVRTexLib_SetTexturePixelFormat() {return 0;}
EXPORT int PVRTexLib_SetTextureVulkanFormat() {return 0;}
EXPORT int PVRTexLib_SetTextureWidth() {return 0;}
EXPORT int PVRTexLib_StandardDeviation() {return 0;}
EXPORT int PVRTexLib_TextureCreateRaw() {return 0;}
EXPORT int PVRTexLib_TextureHasMetaData() {return 0;}
EXPORT int PVRTexLib_TextureHasPackedChannelData() {return 0;}
EXPORT int PVRTexLib_TextureLoadTiled() {return 0;}
EXPORT int PVRTexLib_ToleranceDiff() {return 0;}
EXPORT int PVRTexLib_TranscodeTexture() {return 0;}